name: Auto-Compile LaTeX and Release

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - '**/*.tex' # Any LaTeX file change in the repo

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Set a reasonable timeout, should be enough for XeLaTeX only

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up TeX Live environment (XeLaTeX only)
      uses: TeX-Live/setup-texlive-action@v2
      with:
        # Use a smaller profile to speed up installation
        profile: medium-scheme # or 'minimal-scheme' if you want even smaller
        # Explicitly install packages needed for XeLaTeX and common fonts
        packages: |
          collection-xetex
          collection-fontsrecommended
          collection-latexrecommended
          collection-binex
          collection-pictures
          collection-science
          collection-publishers
          collection-humanities
          biber # Needed if you decide to use biblatex in the future
          latexmk # Tool for robust compilation, used by default with xu-cheng/latex-action
          amsfonts # Explicitly add if not covered by recommended collections
          amsmath # Explicitly add if not covered by recommended collections
          amssymb # Explicitly add if not covered by recommended collections
          amsthm # Explicitly add if not covered by recommended collections
          mathtools # Explicitly add if not covered by recommended collections
          bm # Explicitly add if not covered by recommended collections
          physics # Explicitly add if not covered by recommended collections
          slashed # Explicitly add if not covered by recommended collections
          fancyhdr # Explicitly add if not covered by recommended collections
          microtype # Explicitly add if not covered by recommended collections
          xcolor # Explicitly add if not covered by recommended collections
          hyperref # Explicitly add if not covered by recommended collections
          cleveref # Explicitly add if not covered by recommended collections
          enumitem # CRITICAL: Explicitly ensure enumitem is installed
          xparse # Explicitly add if not covered by recommended collections
          xecjk # Explicitly add for CJK support (as you use xeCJK in preamble)
          fontspec # Explicitly add for font selection with XeLaTeX
          texgyre # Explicitly add for TeX Gyre Termes font
          noto # Explicitly add for Noto Serif CJK JP font

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      id: compile_latex
      with:
        root_file: main.tex
        args: -xelatex -file-line-error -interaction=nonstopmode # Ensure xelatex is used

    - name: Check for compiled PDF
      run: |
        if [ ! -f main.pdf ]; then
          echo "Error: main.pdf was not created by LaTeX compilation."
          exit 1
        else
          echo "main.pdf successfully created."
        fi

    - name: Create Release and Upload PDF
      id: create_release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/heads/main')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Auto-Release ${{ github.run_number }}
        body: |
          Automated release for ${{ github.event.repository.name }}.
          Version: ${{ github.run_number }}

          This content is unreviewed and actively being developed. Use at your own risk.
        files: |
          main.pdf
