name: Auto-Compile LaTeX and Release

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - '**/*.tex' # Any LaTeX file change in the repo

jobs:
  build_and_release:
    runs-on: ubuntu-latest # Standard runner
    timeout-minutes: 15 # Set a generous timeout

    container: # Job runs inside this Docker container
      image: "ghcr.io/xu-cheng/texlive-full:latest" # Pre-built image with full TeX Live

    steps: # List of steps in the job
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile LaTeX (Force Max Compatibility and Error Handling)
      uses: xu-cheng/latex-action@v2
      id: compile_latex
      with:
        root_file: main.tex
        compiler: pdflatex # Using pdflatex for maximum robustness
        args: -file-line-error -interaction=nonstopmode -halt-on-error=false -output-directory=/github/workspace
        ignore_errors: true # Force the action to report success for this step even with LaTeX errors
      continue-on-error: true # Ensure the *workflow step* itself doesn't fail the job

    - name: Check for compiled PDF
      run: |
        if [ ! -f main.pdf ]; then
          echo "Warning: main.pdf was NOT created by LaTeX compilation. This means the LaTeX document is severely broken. No PDF will be attached to the release."
        else
          echo "main.pdf successfully created. It may be a partial or error-ridden PDF."
        fi

    - name: Create Release and Upload PDF
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/heads/main')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Auto-Release ${{ github.run_number }}
        body: |
          Automated release for ${{ github.event.repository.name }}.
          Version: ${{ github.run_number }}

          This content is unreviewed and actively being developed. This release attempts to provide a PDF even if the LaTeX compilation has errors. Use at your own risk.
        files: |
          main.pdf # Will attempt to attach main.pdf. If it doesn't exist, this step might fail gracefully or attach nothing.
