name: Auto-Compile LaTeX and Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tex'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write

    container:
      image: "ghcr.io/xu-cheng/texlive-full:latest"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile LaTeX (Force Max Compatibility and Error Handling)
      uses: xu-cheng/latex-action@v2
      id: compile_latex
      with:
        root_file: main.tex
        compiler: xelatex
        args: -file-line-error -interaction=nonstopmode -halt-on-error=false -output-directory=/github/workspace
        ignore_errors: true
      continue-on-error: true

    - name: Check for compiled PDF
      run: |
        if [ ! -f main.pdf ]; then
          echo "Error: main.pdf was NOT created by LaTeX compilation. Check Compile LaTeX step logs. Releasing anyway."
          exit 1
        else
          echo "main.pdf successfully created. It may be a partial or error-ridden PDF."
        fi

    - name: Create Release and Upload PDF
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/heads/main')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Auto-Release ${{ github.run_number }}
        body: |
          Automated release for ${{ github.event.repository.name }}.
          Version: ${{ github.run_number }}

          This content is unreviewed and actively being developed. This release attempts to provide a PDF even if the LaTeX compilation has errors. Use at your own risk.
        files: |
          main.pdf
