name: Auto-Compile LaTeX and Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tex'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write # Needed for creating GitHub Releases

    container:
      image: "ghcr.io/xu-cheng/texlive-full:latest" # Pre-built image with full TeX Live

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile LaTeX (Force Max Compatibility and Error Handling)
      uses: xu-cheng/latex-action@v2
      id: compile_latex
      with:
        root_file: main.tex
        compiler: xelatex
        args: -file-line-error -interaction=nonstopmode -halt-on-error=false -output-directory=/github/workspace
        ignore_errors: true
      continue-on-error: true

    - name: Check for compiled PDF
      id: check_pdf
      run: |
        if [ ! -f main.pdf ]; then
          echo "Error: main.pdf was NOT created by LaTeX compilation. Check Compile LaTeX step logs."
          echo "pdf_exists=false" >> $GITHUB_OUTPUT
          exit 1 # Fail job if PDF is genuinely missing
        else
          echo "main.pdf successfully created. It may be a partial or error-ridden PDF."
          echo "pdf_exists=true" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release and Attach PDF
      # This step runs AFTER PDF is created.
      # It attaches main.pdf as a separate asset to the GitHub Release.
      # It does NOT commit main.pdf to the Git repository.
      uses: softprops/action-gh-release@v2
      if: steps.check_pdf.outputs.pdf_exists == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Auto-Release ${{ github.run_number }}
        body: |
          Automated release for ${{ github.event.repository.name }}.
          Version: ${{ github.run_number }}
          This content is unreviewed and actively being developed. Use at your own risk.
        files: | # This attaches main.pdf as a separate asset to the release.
          main.pdf
