name: Auto-Compile LaTeX and Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tex'

jobs:
  build_release_asset:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write

    container:
      image: "ghcr.io/xu-cheng/texlive-full:latest"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Utilities
      run: apk update && apk add zip jq

    - name: Compile LaTeX (Force Max Compatibility and Error Handling)
      uses: xu-cheng/latex-action@v2
      id: compile_latex
      with:
        root_file: main.tex
        compiler: xelatex
        args: -file-line-error -interaction=nonstopmode -halt-on-error=false -output-directory=/github/workspace -f -latexoption="-halt-on-error=false -interaction=nonstopmode"
        ignore_errors: true
      continue-on-error: true

    - name: Prepare PDF and source files for Release (ZIP it up)
      id: prepare_content
      run: |
        RELEASE_DIR="release_content"
        mkdir -p "$RELEASE_DIR"

        if [ -f "main.pdf" ]; then
          mv "main.pdf" "$RELEASE_DIR/main.pdf"
        else
          echo "PDF compilation failed or PDF not found. Placeholder created."
          echo "No main.pdf generated." > "$RELEASE_DIR/compilation_failed.txt"
        fi

        find . -maxdepth 1 -name "*.tex" -exec cp {} "$RELEASE_DIR/" \;

        zip -r "${{ github.event.repository.name }}_release_${{ github.run_number }}.zip" "$RELEASE_DIR/"

        echo "release_zip_name=${{ github.event.repository.name }}_release_${{ github.run_number }}.zip" >> "$GITHUB_OUTPUT"
        echo "content_ready=true" >> "$GITHUB_OUTPUT"

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      if: steps.prepare_content.outputs.content_ready == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Automated Release ${{ github.run_number }}
        body: |
          Latest automated build and release of the physics work.
        files: |
          ${{ steps.prepare_content.outputs.release_zip_name }}
