name: Auto-Compile LaTeX and Release

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - '**/*.tex' # Any LaTeX file change in the repo

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Set a generous timeout

    container: # Use a specific Docker container for the job
      image: "ghcr.io/xu-cheng/texlive-full:latest" # This image has full TeX Live (including XeLaTeX) pre-installed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      id: compile_latex
      with:
        root_file: main.tex
        # Explicitly set the compiler to xelatex, and remove conflicting args or defaults
        compiler: xelatex
        args: -file-line-error -interaction=nonstopmode # Ensure -no-pdf is NOT here
        # The output PDF will be in the working directory (/github/workspace/main.pdf by default)

    - name: Check for compiled PDF
      run: |
        if [ ! -f main.pdf ]; then
          echo "Error: main.pdf was not created by LaTeX compilation. Check Compile LaTeX step logs."
          exit 1
        else
          echo "main.pdf successfully created."
        fi

    - name: Create Release and Upload PDF
      id: create_release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/heads/main')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Auto-Release ${{ github.run_number }}
        body: |
          Automated release for ${{ github.event.repository.name }}.
          Version: ${{ github.run_number }}

          This content is unreviewed and actively being developed. Use at your own risk.
        files: |
          main.pdf
