name: Auto-Compile LaTeX and Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tex'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write

    container:
      image: "ghcr.io/xu-cheng/texlive-full:latest"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Ensure Zip Utility is installed
      run: apk update && apk add zip

    - name: Compile LaTeX (Force Max Compatibility and Error Handling)
      uses: xu-cheng/latex-action@v2
      id: compile_latex
      with:
        root_file: main.tex
        compiler: xelatex
        args: -file-line-error -interaction=nonstopmode -halt-on-error=false -output-directory=/github/workspace -f -latexoption="-halt-on-error=false -interaction=nonstopmode"
        ignore_errors: true
      continue-on-error: true

    - name: Prepare PDF for Release (ZIP it up)
      id: prepare_pdf_zip
      run: |
        PDF_FILE="main.pdf"
        ZIP_FILE="${{ github.event.repository.name }}_release_${{ github.run_number }}.zip"

        if [ ! -f "$PDF_FILE" ]; then
          touch empty_placeholder.txt
          zip "$ZIP_FILE" empty_placeholder.txt
          echo "zip_created=true" >> "$GITHUB_OUTPUT"
          echo "zip_file_name=$ZIP_FILE" >> "$GITHUB_OUTPUT"
        else
          mkdir -p release_content
          mv "$PDF_FILE" release_content/
          zip -r "$ZIP_FILE" release_content/
          echo "zip_created=true" >> "$GITHUB_OUTPUT"
          echo "zip_file_name=$ZIP_FILE" >> "$GITHUB_OUTPUT"
        fi

    - name: Create Release and Upload ZIP
      uses: softprops/action-gh-release@v2
      if: steps.prepare_pdf_zip.outputs.zip_created == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Auto-Release ${{ github.run_number }}
        body: |
          Automated release for ${{ github.event.repository.name }}.
          Version: ${{ github.run_number }}

          This content is unreviewed and actively being developed. This release attempts to provide a PDF even if the LaTeX compilation has errors. Use at your own risk.
        files: |
          ${{ steps.prepare_pdf_zip.outputs.zip_file_name }}
