name: Compile PDF and Commit to Repo

on:
  push:
    branches:
      - main

jobs:
  build_and_commit_pdf:
    # Do not run on commits made by the action itself
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Compile LaTeX to PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        compiler: xelatex
        args: -file-line-error -interaction=nonstopmode -halt-on-error=false
      continue-on-error: true

    - name: Commit and Push PDF
      run: |
        if [ ! -f main.pdf ]; then
          echo "main.pdf not created by LaTeX. Halting."
          exit 1
        fi
        
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Add the PDF file. This will stage it for commit,
        # replacing the old one if it exists.
        git add main.pdf
        
        # Commit only if there are changes to the PDF
        if ! git diff --staged --quiet; then
          git commit -m "Automated: Update generated PDF [skip ci]"
          git push
        else
          echo "PDF has not changed. No commit needed."
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Automated Release ${{ github.run_number }}
        body: |
          Latest automated build. The PDF is included directly in the source code for this tag.
