name: Auto-Compile LaTeX and Release

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - '**/*.tex' # Any LaTeX file change in the repo

jobs:
  build_and_release:
    runs-on: ubuntu-latest # Standard runner, but we'll use a Docker image inside
    timeout-minutes: 15 # Set a generous timeout for the overall job, though it should be fast now

    container: # Use a specific Docker container for the job
      image: "ghcr.io/xu-cheng/texlive-full:latest" # This image has full TeX Live (including XeLaTeX) pre-installed
      # Alternatives if this one has issues or is too large:
      # image: "ghcr.io/latex_actions/latex:latest" (lighter, but might need manual package install for specific fonts)
      # image: "pandoc/latex:latest" (also pre-built TeX Live)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # REMOVED: No need for setup-texlive-action or manual apt-get install
    # as TeX Live is already in the Docker image.

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      id: compile_latex
      with:
        root_file: main.tex
        args: -xelatex -file-line-error -interaction=nonstopmode # Ensure xelatex is used

    - name: Check for compiled PDF
      run: |
        if [ ! -f main.pdf ]; then
          echo "Error: main.pdf was not created by LaTeX compilation."
          exit 1
        else
          echo "main.pdf successfully created."
        fi

    - name: Create Release and Upload PDF
      id: create_release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/heads/main')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Auto-Release ${{ github.run_number }}
        body: |
          Automated release for ${{ github.event.repository.name }}.
          Version: ${{ github.run_number }}

          This content is unreviewed and actively being developed. Use at your own risk.
        files: |
          main.pdf
